### ISSUE TITLE
Add relative time in the future

### ISSUE THREAD

**Issue by theldoria** [rougier/relative-date#1]
I would like to use this also for appointments, which tend to be in the future :wink:.

So for example:

```elisp
(let ((now  (encode-time (parse-time-string "2022-07-14 8:00")))
      (date (encode-time (parse-time-string "2022-07-14 6:05"))))
  (relative-date now date))
;; -> "in 2 hours"
```

**Comment by rougier** [comment]
Good idea. Should not be too difficult to implement. I just need some free time to do it. Do not hesitate to remind me here.

**Comment by rougier** [comment]
Done.
